create table if not exists products (
  id text primary key,
  name text not null,
  category text,
  description text,
  price integer not null,
  promo_price integer,
  status text default 'Disponible',
  image text,
  created_at timestamptz default now()
);
create table if not exists clients (
  id bigint generated by default as identity primary key,
  name text,
  phone text unique not null,
  city text,
  address text,
  created_at timestamptz default now()
);
create table if not exists orders (
  id bigint generated by default as identity primary key,
  client_id bigint references clients(id),
  product_id text references products(id),
  quantity integer not null default 1,
  unit_price integer not null,
  total integer not null,
  status text default 'En attente',
  payment_status text default 'En attente',
  payment_method text,
  delivery text,
  notes text,
  created_at timestamptz default now()
);
create table if not exists messages (
  id bigint generated by default as identity primary key,
  phone text not null,
  direction text not null,
  text text,
  created_at timestamptz default now()
);
create table if not exists conversations (
  phone text primary key,
  state text default 'idle',
  data jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);
create table if not exists quote_requests (
  id bigint generated by default as identity primary key,
  phone text not null,
  request text not null,
  status text default 'Nouveau',
  created_at timestamptz default now()
);
